# Generated by Django 5.0.6 on 2024-06-25 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('temperature', models.CharField(max_length=500)),
                ('caffeine_amount', models.CharField(max_length=200)),
                ('price', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('product_name', models.CharField(max_length=200, null=True)),
                ('price', models.CharField(max_length=500)),
            ],
        ),
    ]
